'use client'

import React from 'react'
import { Card } from '@/components/ui/Card'
import { LoadingSpinner } from '@/components/ui/LoadingSpinner'

interface AISummaryProps {
  forSummary?: string
  againstSummary?: string
  loading?: boolean
}

export const AISummary: React.FC<AISummaryProps> = ({
  forSummary,
  againstSummary,
  loading,
}) => {
  if (loading) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <Card className="p-6 bg-blue-50 border-blue-200">
          <div className="flex items-center justify-center py-8">
            <LoadingSpinner />
          </div>
        </Card>
        <Card className="p-6 bg-yellow-50 border-yellow-200">
          <div className="flex items-center justify-center py-8">
            <LoadingSpinner />
          </div>
        </Card>
      </div>
    )
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
      {/* For Summary */}
      <Card className="p-6 bg-blue-50 border-blue-200">
        <h3 className="text-lg font-semibold text-gray-900 mb-2">
          Leading Position Summary (For)
        </h3>
        {forSummary ? (
          <p className="text-gray-700 leading-relaxed">{forSummary}</p>
        ) : (
          <p className="text-gray-500 italic">Summary will be generated when evidence is added.</p>
        )}
      </Card>

      {/* Against Summary (Steel Man) */}
      <Card className="p-6 bg-yellow-50 border-yellow-200">
        <h3 className="text-lg font-semibold text-gray-900 mb-2">
          Steel Man of Opposing View (Against)
        </h3>
        <p className="text-sm text-gray-600 mb-3 italic">
          A fair, thoughtful restatement of the best opposing argument, generated by AI to promote
          deeper understanding
        </p>
        {againstSummary ? (
          <p className="text-gray-700 leading-relaxed">{againstSummary}</p>
        ) : (
          <p className="text-gray-500 italic">Summary will be generated when evidence is added.</p>
        )}
      </Card>
    </div>
  )
}

